### ISSUE TITLE
Leaderboards are capped at 5000 entries

### ISSUE THREAD

**Issue by 3ternal** [Steffo99/steamleaderboards#1]
Hi,

Thanks for making this!

I'm trying it out with Rivals of Aether (app ID 383980), and I noticed that the `entries` variable seems to get capped at 5000. I'm not sure if this is a Steam limitation. I haven't played in the current season, so if I check my rank in the game itself, I'm at position 48,040, but the length of `leaderboard.entries` is still 5000.

The code is pretty much the same as in the readme.

```
import steamleaderboards as sl

lbgroup = sl.LeaderboardGroup(383980)
leaderboard = lbgroup.get(display_name="Ranked All Rivals")

all_scores = leaderboard.entries
my_score = leaderboard.find_entry(<my steam ID string>)
first_place_score = leaderboard.find_entry(rank=1)
last_place_score = leaderboard.find_entry(rank=-1)

print("My score: " + str(my_score) + " out of " + str(last_place_score))
print("Total entries: " + str(len(leaderboard.entries)))
```

**Comment by Steffo99** [comment]
Oh, it's cool to see that somebody ended up actually using this! :D  

Let me try this out.

**Comment by Steffo99** [comment]
Ok, I fixed this in my development version!

I should add a configurable limit and rate limiting though. 

Give me a couple more minutes...

**Comment by 3ternal** [comment]
Hey, thanks for the quick fix!

Does the limit keyword only work on command line? It didn't seem to work when I used it as an argument in the `leaderboardgroup.get()` function. It did work on command line, but I don't think you can specify which leaderboard to get, so it ends up downloading all of them.

**Comment by 3ternal** [comment]
Thanks for looking into it. Should this update be added as a release so that `pip` can update it? `steamleaderboards -V` is still giving me `1.1.0`.

**Comment by Steffo99** [comment]
Done!

**Comment by 3ternal** [comment]
I got the update, but how do we use it? I'm still getting a `LeaderboardGroup.get() got an unexpected keyword argument 'limit'`  error with the following code:

```
import steamleaderboards as sl

lbgroup = sl.LeaderboardGroup(383980)
leaderboard = lbgroup.get(display_name="Ranked All Rivals",limit=1000)
```

**Comment by Steffo99** [comment]
Oh, wait, I forgot how my own library was structured :laughing: 

Sorry, I made this ages ago and pushed an update just to make sure it still worked and to add an icon to the README...

Adding kwargs to `get` right now!

**Comment by Steffo99** [comment]
Try v1.1.2!

You might want to use `--no-cache-dir` with pip or it might not immediately detect the upgrade:

```python
pip install steamleaderboards --no-cache-dir --upgrade
```

**Comment by 3ternal** [comment]
There we go! All working now, thanks.
